In [1]:
import pandas as pd
df = pd.read_csv("https://gist.githubusercontent.com/singhsidhukuldeep/7ac8d27e45da971de1f280366cd5537b/raw/d8342e78fb54133d5abdd366bd1d83c664e1347b/final_vg.csv")
df.head()

Rank                               Name Platform    Year         Genre  \
0   2061                               1942      NES  1985.0       Shooter   
1   9137       ¡Shin Chan Flipa en colores!       DS  2007.0      Platform   
2  14279  .hack: Sekai no Mukou ni + Versus      PS3  2012.0        Action   
3   8359         .hack//G.U. Vol.1//Rebirth      PS2  2006.0  Role-Playing   
4   7109       .hack//G.U. Vol.2//Reminisce      PS2  2006.0  Role-Playing   

            Publisher  NA_Sales  EU_Sales  JP_Sales  Other_Sales  Global_Sales  
0              Capcom  4.569217  3.033887  3.439352     1.991671     12.802935  
1           505 Games  2.076955  1.493442  3.033887     0.394830      7.034163  
2  Namco Bandai Games  1.145709  1.762339  1.493442     0.408693      4.982552  
3  Namco Bandai Games  2.031986  1.389856  3.228043     0.394830      7.226880  
4  Namco Bandai Games  2.792725  2.592054  1.440483     1.493442      8.363113

In [ ]:
#Generally Python stores the location of the Elemant not the original data
#
#we generally use the and store tge data

# Then the numpy comes into the picture like you can store the data in numpy,it should be same datatype only
# benefit of numpy is without using loops in it.


Average Temperature per City: 29.466666666666665
Hottest Day for Each City: [4 4 5]
Future Temperature Data (All +1°C):
 [[31 26 29]
 [33 28 31]
 [30 27 32]
 [36 29 30]
 [34 28 33]]


In [ ]:
import math as m
print(m.log(55))

4.007333185232471


In [ ]:
!pip install numpy


In [ ]:
!pip install streamlit

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 44.3/44.3 kB 2.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.1/9.1 MB 89.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.9/6.9 MB 86.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 79.1/79.1 kB 5.3 MB/s eta 0:00:00


In [ ]:
import numpy as np
a = [1,2,3,4,5]
b=np.array(a)
print(b)
type(b)

# nd.array means nd as like ndimensional arrays
#To square we have to do like

print(b**2)
#numpy will go to every element without using any loops
print(b-2)#subtracting+2
print(b+2)#adding +2
print(b*2) #multiplying by *2

[1 2 3 4 5]
[ 1  4  9 16 25]


In [ ]:
import numpy as np
arr = np.array([1,2,3,5])
print(arr)
print(arr.ndim)  #To see how many dimensions are there
print(arr.shape)

[1 2 3 5]
1
(4,)


In [ ]:
import numpy as np
arr = np.array([
    [1,2,3,5],
    [5,9,8,5],
    [99,6,4,1]])
print(arr)
print(arr.ndim) #To see how many dimensions are there
print(arr.shape) #To see shape of teh array
print(arr.shape[0]*arr.shape[1]) # How many elements in the Array
print(arr.dtype) # what data type am using

[[ 1  2  3  5]
 [ 5  9  8  5]
 [99  6  4  1]]
2
(3, 4)
12
int64


In [ ]:
print(list(range(5)))
print(list(range(1,5)))
print(list(range(1,15,3)))


[0, 1, 2, 3, 4]
[1, 2, 3, 4]
[1, 4, 7, 10, 13]


In [ ]:
#NP arrange comes up

lst = [1.2,3.5,6.2,6.4,9.9]
print(np.arange(1,15,3.5))

[ 1.   4.5  8.  11.5]


In [ ]:
arr = np.linspace(1,10,8)
print(arr[0]-arr[1])
print(arr[1]-arr[2])
print(arr[2]-arr[3])
print(arr[3]-arr[4])
print(arr[4]-arr[5])


-1.2857142857142856
-1.285714285714286
-1.285714285714286
-1.2857142857142856
-1.2857142857142856


In [ ]:
lst =[1,2,3,'mani',4]
arr = np.array()
print(arr.dtype)
print(arr)


<U21
['1' '2' '3' 'mani' '4']


In [ ]:
!gdown https://drive.google.com/uc?id=1vk1Pu0djiYcrdc85yUXZ_Rqq2oZNcohd


Downloading...
From: https://drive.google.com/uc?id=1vk1Pu0djiYcrdc85yUXZ_Rqq2oZNcohd
To: /content/fit.txt
100% 3.43k/3.43k [00:00<00:00, 11.4MB/s]


In [ ]:
np.loadtext('/content/fit.txt')