In [ ]:
!gdown https://drive.google.com/uc?id=1vk1Pu0djiYcrdc85yUXZ_Rqq2oZNcohd


Downloading...
From: https://drive.google.com/uc?id=1vk1Pu0djiYcrdc85yUXZ_Rqq2oZNcohd
To: /content/fit.txt
100% 3.43k/3.43k [00:00<00:00, 9.39MB/s]


In [ ]:

# To load text
import numpy as np
data=np.loadtxt('/content/fit.txt',dtype='str') #changed all data type to str

In [ ]:
print(data.shape)

(96, 6)


In [ ]:
print(data[0])

['06-10-2017' '5464' 'Neutral' '181' '5' 'Inactive']


In [ ]:
print(data)

[['06-10-2017' '5464' 'Neutral' '181' '5' 'Inactive']
 ['07-10-2017' '6041' 'Sad' '197' '8' 'Inactive']
 ['08-10-2017' '25' 'Sad' '0' '5' 'Inactive']
 ['09-10-2017' '5461' 'Sad' '174' '4' 'Inactive']
 ['10-10-2017' '6915' 'Neutral' '223' '5' 'Active']
 ['11-10-2017' '4545' 'Sad' '149' '6' 'Inactive']
 ['12-10-2017' '4340' 'Sad' '140' '6' 'Inactive']
 ['13-10-2017' '1230' 'Sad' '38' '7' 'Inactive']
 ['14-10-2017' '61' 'Sad' '1' '5' 'Inactive']
 ['15-10-2017' '1258' 'Sad' '40' '6' 'Inactive']
 ['16-10-2017' '3148' 'Sad' '101' '8' 'Inactive']
 ['17-10-2017' '4687' 'Sad' '152' '5' 'Inactive']
 ['18-10-2017' '4732' 'Happy' '150' '6' 'Active']
 ['19-10-2017' '3519' 'Sad' '113' '7' 'Inactive']
 ['20-10-2017' '1580' 'Sad' '49' '5' 'Inactive']
 ['21-10-2017' '2822' 'Sad' '86' '6' 'Inactive']
 ['22-10-2017' '181' 'Sad' '6' '8' 'Inactive']
 ['23-10-2017' '3158' 'Neutral' '99' '5' 'Inactive']
 ['24-10-2017' '4383' 'Neutral' '143' '4' 'Inactive']
 ['25-10-2017' '3881' 'Neutral' '125' '5' 'Inactive'

In [ ]:
print(data[:5])  # To print first 5 rows of data

[['06-10-2017' '5464' 'Neutral' '181' '5' 'Inactive']
 ['07-10-2017' '6041' 'Sad' '197' '8' 'Inactive']
 ['08-10-2017' '25' 'Sad' '0' '5' 'Inactive']
 ['09-10-2017' '5461' 'Sad' '174' '4' 'Inactive']
 ['10-10-2017' '6915' 'Neutral' '223' '5' 'Active']]


In [ ]:
arr = np.arange(16)
print(arr.shape)
print(arr.reshape(8,2))
print(arr.reshape(4,4))

(16,)
[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [ ]:
arr2_2_4 = arr.reshape(2,2,4)
print(arr2_2_4)

[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]]


In [ ]:
print(arr2_2_4[0])

[[0 1 2 3]
 [4 5 6 7]]


In [ ]:
import numpy as np
arr = np.arange(12).reshape(4,3)
print(arr)


[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [ ]:
print(arr[2,1])

7


In [ ]:
#  To Transpose an array
arr_T =arr.T
print(arr_T )

[[ 0  3  6  9]
 [ 1  4  7 10]
 [ 2  5  8 11]]


In [ ]:
arr = np.array([10,20,30,40,50,60,70,80,90])

print(arr[[2,1]])


[30 20]


In [ ]:
arr =np.arange(12).reshape(4,3)
print(arr)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [ ]:
print(arr[ [2,3],[0,0]      ])
print(arr[ [2,3],[1,1]      ])

[6 9]
[ 7 10]


In [ ]:
print(data)

[['06-10-2017' '5464' 'Neutral' '181' '5' 'Inactive']
 ['07-10-2017' '6041' 'Sad' '197' '8' 'Inactive']
 ['08-10-2017' '25' 'Sad' '0' '5' 'Inactive']
 ['09-10-2017' '5461' 'Sad' '174' '4' 'Inactive']
 ['10-10-2017' '6915' 'Neutral' '223' '5' 'Active']
 ['11-10-2017' '4545' 'Sad' '149' '6' 'Inactive']
 ['12-10-2017' '4340' 'Sad' '140' '6' 'Inactive']
 ['13-10-2017' '1230' 'Sad' '38' '7' 'Inactive']
 ['14-10-2017' '61' 'Sad' '1' '5' 'Inactive']
 ['15-10-2017' '1258' 'Sad' '40' '6' 'Inactive']
 ['16-10-2017' '3148' 'Sad' '101' '8' 'Inactive']
 ['17-10-2017' '4687' 'Sad' '152' '5' 'Inactive']
 ['18-10-2017' '4732' 'Happy' '150' '6' 'Active']
 ['19-10-2017' '3519' 'Sad' '113' '7' 'Inactive']
 ['20-10-2017' '1580' 'Sad' '49' '5' 'Inactive']
 ['21-10-2017' '2822' 'Sad' '86' '6' 'Inactive']
 ['22-10-2017' '181' 'Sad' '6' '8' 'Inactive']
 ['23-10-2017' '3158' 'Neutral' '99' '5' 'Inactive']
 ['24-10-2017' '4383' 'Neutral' '143' '4' 'Inactive']
 ['25-10-2017' '3881' 'Neutral' '125' '5' 'Inactive'

In [ ]:
print(data[:,1])

['5464' '6041' '25' '5461' '6915' '4545' '4340' '1230' '61' '1258' '3148'
 '4687' '4732' '3519' '1580' '2822' '181' '3158' '4383' '3881' '4037'
 '202' '292' '330' '2209' '4550' '4435' '4779' '1831' '2255' '539' '5464'
 '6041' '4068' '4683' '4033' '6314' '614' '3149' '4005' '4880' '4136'
 '705' '570' '269' '4275' '5999' '4421' '6930' '5195' '546' '493' '995'
 '1163' '6676' '3608' '774' '1421' '4064' '2725' '5934' '1867' '3721'
 '2374' '2909' '1648' '799' '7102' '3941' '7422' '437' '1231' '1696'
 '4921' '221' '6500' '3575' '4061' '651' '753' '518' '5537' '4108' '5376'
 '3066' '177' '36' '299' '1447' '2599' '702' '133' '153' '500' '2127'
 '2203']


In [ ]:
data_T = data.T
print(data_T[0])

['06-10-2017' '07-10-2017' '08-10-2017' '09-10-2017' '10-10-2017'
 '11-10-2017' '12-10-2017' '13-10-2017' '14-10-2017' '15-10-2017'
 '16-10-2017' '17-10-2017' '18-10-2017' '19-10-2017' '20-10-2017'
 '21-10-2017' '22-10-2017' '23-10-2017' '24-10-2017' '25-10-2017'
 '26-10-2017' '27-10-2017' '28-10-2017' '29-10-2017' '30-10-2017'
 '31-10-2017' '01-11-2017' '02-11-2017' '03-11-2017' '04-11-2017'
 '05-11-2017' '06-11-2017' '07-11-2017' '08-11-2017' '09-11-2017'
 '10-11-2017' '11-11-2017' '12-11-2017' '13-11-2017' '14-11-2017'
 '15-11-2017' '16-11-2017' '17-11-2017' '18-11-2017' '19-11-2017'
 '20-11-2017' '21-11-2017' '22-11-2017' '23-11-2017' '24-11-2017'
 '25-11-2017' '26-11-2017' '27-11-2017' '28-11-2017' '29-11-2017'
 '30-11-2017' '01-12-2017' '02-12-2017' '03-12-2017' '04-12-2017'
 '05-12-2017' '06-12-2017' '07-12-2017' '08-12-2017' '09-12-2017'
 '10-12-2017' '11-12-2017' '12-12-2017' '13-12-2017' '14-12-2017'
 '15-12-2017' '16-12-2017' '17-12-2017' '18-12-2017' '19-12-2017'
 '20-12-20

In [ ]:
arr=np.arange(12).reshape(4,3)
print(np.sum(arr))
print(np.min(arr))
print(np.max(arr))
print(np.mean(arr))


66
0
11
5.5


In [ ]:
print(np.sum(arr ,axis=1))   # axis is 0 means going to vertical line
print(np.sum(arr,axis=1))    # axis is 1 means going to horizontal axis like we manipulating at the horintal wise only

[ 3 12 21 30]
[ 3 12 21 30]


In [ ]:
arr=np.arange(12).reshape(3,4)
print(np.sum(arr,axis=0))
print(np.min(arr,axis=0))
print(np.max(arr,axis=0))
print(np.mean(arr,axis=0))

print("------------------------")
print(np.sum(arr,axis=1))
print(np.min(arr,axis=1))
print(np.max(arr,axis=1))
print(np.mean(arr,axis=1))


[12 15 18 21]
[0 1 2 3]
[ 8  9 10 11]
[4. 5. 6. 7.]
------------------------
[ 6 22 38]
[0 4 8]
[ 3  7 11]
[1.5 5.5 9.5]


In [ ]:
# To check the Greater Than or less Than
a=np.array([1,2,3,4])
b=np.array([4,2,5,8])
print(a<b)

[ True False  True  True]
